name: Doctrine schema validatie

on:
  pull_request:
    branches: [ master, development ]
  push:
    branches: [ master, development ]

jobs:
  schema-validate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Draai schemavalidatie
      run: exit 1
